version: "3.1"

services:
  postgres-server:
    image: postgres:13
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PGDATA: /data/postgres
    volumes:
      - /d01/postgres_dat:/data/postgres
    ports:
      - 5432:5432

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.2.0
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:
      - ./alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2.0
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Asia/Tehran"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8080:8080

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.2.0
    privileged: true
    network_mode: "host"
    environment:
      - ZBX_SERVER_HOST=zabbix-server

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.2.0
    ports:
      - 10052:10052
    depends_on:
      - postgres-server
      - zabbix-server


volumes:
  postgres_data:
    driver: local
